# Generated by Django 2.0.4 on 2018-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='escuela',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre_programa',
            field=models.CharField(max_length=50),
        ),
    ]
