# Generated by Django 2.0.4 on 2018-04-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='numero_creditos_graduacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programa',
            name='numero_semestres',
            field=models.IntegerField(),
        ),
    ]
