# Generated by Django 2.0.4 on 2018-04-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0002_programa_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.TextField(blank=True, choices=[('admin', 'Administrador'), ('decano', 'Decano'), ('director', 'Director'), ('profesor', 'Profesor')], max_length=500),
        ),
    ]
