# Generated by Django 2.0.4 on 2018-04-18 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0003_auto_20180417_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='director',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
