# Generated by Django 2.0.4 on 2018-04-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0003_curso_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_curso',
            field=models.CharField(choices=[('Asignatura basica', 'Asignatura basica'), ('Asignatura profesional', 'Asignatura profesional'), ('Asignatura electiva complementaria', 'Asignatura electiva complementaria'), ('Asignatura electiva profesional', 'Asignatura electiva profesional')], max_length=50),
        ),
    ]
