# Generated by Django 2.0.4 on 2018-04-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0004_auto_20180415_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre_programa', models.CharField(max_length=255)),
                ('escuela', models.CharField(max_length=255)),
                ('numero_semestres', models.CharField(max_length=255)),
                ('numero_creditos_graduacion', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
