# Generated by Django 2.0.4 on 2018-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0004_auto_20180415_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('creditos', models.IntegerField()),
                ('horas_clase_magistral', models.IntegerField()),
                ('horas_estudio_independiente', models.IntegerField()),
                ('tipo_curso', models.CharField(max_length=20)),
                ('validable', models.CharField(max_length=2)),
                ('habilitable', models.CharField(max_length=2)),
                ('programa', models.CharField(max_length=20)),
                ('semestre', models.IntegerField()),
            ],
        ),
    ]
