# Generated by Django 2.0.4 on 2018-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0005_programa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ('codigo',)},
        ),
        migrations.RemoveField(
            model_name='programa',
            name='id',
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
